apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    secrets.doppler.com/reload: "true"
  creationTimestamp: null
  labels:
    app: keeper-app
  name: keeper-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keeper-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: keeper-app
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: dev-keeper-app-secrets
        image: 721574006748.dkr.ecr.us-east-1.amazonaws.com/dev-saas-zebec:keeper-app-dev-21116966c057075e5b679b06cb3eedf3be66f025
        name: keeper-app
        resources: {}
status: {}
