apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    secrets.doppler.com/reload: "true"
  creationTimestamp: null
  labels:
    app: liquidator-app
  name: liquidator-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liquidator-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: liquidator-app
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: dev-liquidator-app-secrets
        image: 721574006748.dkr.ecr.us-east-1.amazonaws.com/dev-saas-zebec:liquidator-app-dev-b4f1201115914856dd717d36cfa7118f86fa836d
        name: liquidator-app
        resources: {}
status: {}
