version: "3"
services:
    chatbox-app:
        build:
            dockerfile: ./packages/siwe-chat-box-backend/Dockerfile
            context: ../../
        ports:
            - "${PORT}:${PORT}"
        volumes:
            - ./:/app
            - /app/node_modules
        environment:
            POSTGRES_HOST: postgres-db
            POSTGRES_PORT: 5432
        env_file:
            - ./.env
        depends_on:
            - postgres-db

    postgres-db:
        image: postgres:14.6
        ports:
            - "5433:5433"
        env_file:
            - ./.env
        volumes:
            - postgres-db:/data/db

volumes:
    postgres-db:
