name: Test and Build

on:
    pull_request:
        branches:
            - deployment-test

jobs:
    build-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Run quality checks
              uses: ./.github/actions/cache-install

            - name: Test
              run: |
                  RUN=CI yarn test
                  yarn lint
                  yarn format:check
                  yarn build
