name: Test and Build

on:
    pull_request:
        branches:
            - deployment-test

jobs:
    build-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Cache install packages
              uses: ./.github/actions/cache-install

            - name: Check formatting
              run: |
                  yarn nx affected --target=lint --all --base=${{ github.base_ref }}
                  yarn nx format:check --base=${{ github.base_ref }}

            - name: Test
              run: |
                  yarn nx affected --target=test --all --base=${{ github.base_ref }}

            - name: Build
              run: |
                  yarn nx affected --target=build --all --base=${{ github.base_ref }}
